name: Wood Masters Millwork
favicon: null
layout_spectrum: 0.31825
typography_spectrum: 0.97004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020609'
    - '#444034'
    - '#4d8659'
    - '#b8bc97'
    - '#fef1e8'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
