name: Wood Masters Millwork
favicon: null
layout_spectrum: 0.25436
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3e3629'
    - '#bebebe'
    - '#8c8980'
    - '#ab5620'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
