name: Wood Masters Millwork
favicon: null
layout_spectrum: 0.32129
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020609'
    - '#444034'
    - '#4d8659'
    - '#b8bc97'
    - '#fef1e8'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
