name: Wood Masters Millwork
favicon: null
layout_spectrum: 0.4547531430143863
typography_spectrum: 0.6988348227459937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020609'
    - '#444034'
    - '#4d8659'
    - '#b8bc97'
    - '#fef1e8'
  brandStrength: 0.5625
  lightness: 0.2367624759208411
  saturation: 0.42652504961006343
  rhythmicContrast: 0.7503394093364477
purpose: []
