name: Wood Masters Millwork
favicon: null
layout_spectrum: 0.64449
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#528799'
    - '#d7bb94'
    - '#cd7933'
    - '#0a1322'
    - '#f3f3f5'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
